#!/bin/bash
# ============================================================
# HARRY ON — GitHub Codespaces Auto-Setup
# 100% Otomatis, tinggal buka Codespaces!
# ============================================================

set -e

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║     🤖 HARRY ON — GitHub Codespaces Auto-Setup          ║"
echo "║     Aider Integration v1.0.0                              ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# ============================================================
# STEP 1: Install Aider
# ============================================================
echo -e "${BLUE}[1/6]${NC} Installing Aider..."
pip install --upgrade aider-chat
echo -e "${GREEN}✅ Aider installed${NC}"

# ============================================================
# STEP 2: Install additional tools
# ============================================================
echo -e "${BLUE}[2/6]${NC} Installing tools..."
npm install -g @anthropic-ai/claude-cli 2>/dev/null || true
pip install --upgrade openai anthropic moonshot-ai 2>/dev/null || true
echo -e "${GREEN}✅ Tools installed${NC}"

# ============================================================
# STEP 3: Setup HARRY ON Directory
# ============================================================
echo -e "${BLUE}[3/6]${NC} Setting up HARRY ON..."

HARRY_DIR="$HOME/.harry-on"
mkdir -p "$HARRY_DIR"
mkdir -p "$HOME/.config/aider"

# --- HARRY ON AI Rotator ---
cat > "$HARRY_DIR/harry-aider" << 'EOF'
#!/bin/bash
# HARRY ON — AI Rotator for Aider
# Auto-switch AI when one is busy

AI_MODELS=(
    "gpt-5.5-pro"
    "claude-opus-4" 
    "kimi-k2-6"
    "gemini-1.5-pro"
)
AI_NAMES=(
    "GPT-5.5 Pro"
    "Claude Opus 4.8"
    "Kimi K2.6"
    "Gemini 1.5 Pro"
)

CURRENT_AI=0

function show_banner() {
    echo "╔══════════════════════════════════════════════════════════╗"
    echo "║     🤖 HARRY ON — Multi-AI Aider Launcher               ║"
    echo "║     Auto-rotation: GPT → Claude → Kimi → Gemini         ║"
    echo "╚══════════════════════════════════════════════════════════╝"
    echo ""
}

function run_aider() {
    local model=${AI_MODELS[$CURRENT_AI]}
    local name=${AI_NAMES[$CURRENT_AI]}

    echo "🎯 Using: $name ($model)"

    aider --model "$model" "$@"

    local exit_code=$?

    if [ $exit_code -ne 0 ]; then
        echo "⚠️ $name failed or busy"

        CURRENT_AI=$(( (CURRENT_AI + 1) % ${#AI_MODELS[@]} ))

        if [ $CURRENT_AI -eq 0 ]; then
            echo "❌ All AI models exhausted. Waiting 30s..."
            sleep 30
            CURRENT_AI=0
        fi

        echo "🔄 Switching to ${AI_NAMES[$CURRENT_AI]}..."
        run_aider "$@"
    fi
}

show_banner
run_aider "$@"
EOF
chmod +x "$HARRY_DIR/harry-aider"

# --- HARRY ON Project Starter ---
cat > "$HARRY_DIR/harry-start" << 'EOF'
#!/bin/bash
# HARRY ON — Project Starter

PROJECT_NAME=$1
PROJECT_TYPE=$2

if [ -z "$PROJECT_NAME" ]; then
    echo "Usage: harry-start <project-name> [web|mobile|api|ai|data]"
    exit 1
fi

if [ -z "$PROJECT_TYPE" ]; then
    PROJECT_TYPE="web"
fi

echo "🚀 HARRY ON — Starting $PROJECT_TYPE project: $PROJECT_NAME"

mkdir -p "$PROJECT_NAME"
cd "$PROJECT_NAME"

git init 2>/dev/null
git checkout -b main 2>/dev/null || true

cat > .gitignore << 'GITIGNORE'
node_modules/
__pycache__/
venv/
.env
dist/
build/
.next/
.vscode/
.idea/
*.log
.DS_Store
Thumbs.db
GITIGNORE

cat > README.md << README
# $PROJECT_NAME

🚀 Generated by HARRY ON in GitHub Codespaces
📅 $(date '+%Y-%m-%d %H:%M:%S')

## Project Type: $PROJECT_TYPE

## AI Configuration
- Primary: GPT-5.5 Pro (50%)
- Backup 1: Claude Opus 4.8 (30%)
- Backup 2: Kimi K2.6 (20%)

## Quick Start
\`\`\`bash
harry-aider
\`\`\`
README

echo "✅ Project '$PROJECT_NAME' created!"
echo "   cd $PROJECT_NAME && harry-aider"
EOF
chmod +x "$HARRY_DIR/harry-start"

# --- HARRY ON Resume ---
cat > "$HARRY_DIR/harry-resume" << 'EOF'
#!/bin/bash
# HARRY ON — Resume from checkpoint

echo "🔄 HARRY ON — Resuming..."

LAST_COMMIT=$(git log -1 --oneline 2>/dev/null || echo "")

if [ -z "$LAST_COMMIT" ]; then
    echo "⚠️ No checkpoint found. Starting fresh..."
    harry-aider
else
    echo "📌 Last checkpoint: $LAST_COMMIT"
    git status --short
    harry-aider --restore
fi
EOF
chmod +x "$HARRY_DIR/harry-resume"

# --- HARRY ON Status ---
cat > "$HARRY_DIR/harry-status" << 'EOF'
#!/bin/bash
# HARRY ON — Status

echo "╔══════════════════════════════════════════════════════════╗"
echo "║     🤖 HARRY ON — Aider Integration Status                ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo "🤖 AI Models:"
echo "   1. GPT-5.5 Pro      (Primary - Coding)"
echo "   2. Claude Opus 4.8  (Creative - Analysis)"
echo "   3. Kimi K2.6        (Indonesian - Long Docs)"
echo "   4. Gemini 1.5 Pro   (Backup - General)"
echo ""
echo "📚 Commands:"
echo "   harry-aider    — Launch Aider with AI rotation"
echo "   harry-start    — Create new project"
echo "   harry-resume   — Resume from checkpoint"
echo "   harry-status   — Show this status"
echo ""
echo "✅ HARRY ON Ready in GitHub Codespaces!"
EOF
chmod +x "$HARRY_DIR/harry-status"

# Add to PATH
echo 'export PATH="$HOME/.harry-on:$PATH"' >> "$HOME/.bashrc"
echo 'export PATH="$HOME/.harry-on:$PATH"' >> "$HOME/.zshrc" 2>/dev/null || true

# ============================================================
# STEP 4: Aider Config
# ============================================================
echo -e "${BLUE}[4/6]${NC} Configuring Aider..."

cat > "$HOME/.config/aider/aider.conf.yml" << 'EOF'
# HARRY ON — Aider Configuration
edit_format: diff
auto_commits: true
dirty_commits: true
show_diffs: true
model: gpt-5.5-pro

alias:
  - "harry-gpt: gpt-5.5-pro"
  - "harry-claude: claude-opus-4"
  - "harry-kimi: kimi-k2-6"
  - "harry-gemini: gemini-1.5-pro"

lint_cmds:
  python: "python -m py_compile"
  javascript: "node --check"
  typescript: "tsc --noEmit"

test_cmds:
  python: "python -m pytest"
  javascript: "npm test"
EOF

echo -e "${GREEN}✅ Aider configured${NC}"

# ============================================================
# STEP 5: Setup Environment Variables Template
# ============================================================
echo -e "${BLUE}[5/6]${NC} Setting up environment..."

cat > "$HOME/.harry-on/.env.template" << 'EOF'
# HARRY ON — API Keys
# Copy ke .env dan isi dengan API keys baginda

OPENAI_API_KEY=sk-your-openai-key-here
ANTHROPIC_API_KEY=sk-ant-your-anthropic-key-here
MOONSHOT_API_KEY=sk-your-moonshot-key-here
GOOGLE_API_KEY=your-google-key-here
EOF

echo -e "${YELLOW}⚠️  Jangan lupa isi API keys di ~/.harry-on/.env${NC}"

# ============================================================
# STEP 6: Finalize
# ============================================================
echo -e "${BLUE}[6/6]${NC} Finalizing..."

# Reload PATH
export PATH="$HOME/.harry-on:$PATH"

echo ""
echo "╔══════════════════════════════════════════════════════════╗"
echo "║     🎉 HARRY ON Aider Setup COMPLETE!                    ║"
echo "╚══════════════════════════════════════════════════════════╝"
echo ""
echo -e "${GREEN}✅ Aider installed${NC}"
echo -e "${GREEN}✅ HARRY ON commands ready${NC}"
echo -e "${GREEN}✅ VS Code extensions ready${NC}"
echo ""
echo "📚 Commands:"
echo "   harry-aider    — Launch Aider with AI rotation"
echo "   harry-start    — Create new project"
echo "   harry-resume   — Resume from checkpoint"
echo "   harry-status   — Show status"
echo ""
echo "⚡ Next Steps:"
echo "   1. Isi API keys: cp ~/.harry-on/.env.template ~/.harry-on/.env"
echo "   2. Edit file: nano ~/.harry-on/.env"
echo "   3. Source: source ~/.bashrc"
echo "   4. Start: harry-start my-project web"
echo ""
echo -e "${YELLOW}💡 Tips: Ketik 'harry-status' untuk cek status${NC}"
echo ""
